### ISSUE TITLE
Deployment fails during SplunkCM EC2 Instance Creation 

### ISSUE THREAD

**Issue by auzroz** [aws-quickstart/quickstart-splunk-enterprise#33]
I have attempted to remove the UserData from the SplunkCM resource, but the deployment then times out. Still troubleshooting this one.

**Comment by auzroz** [comment]
Looks like it is related to the following line in the UserData, this is present in all Instances. Based on running the exact command on the AMI manually, it throws an error where the sed command strips the variable out.
`sed -i 's/ENFORCE_PWD_CHANGE=1//' /etc/init.d/splunk\n`
This appears to alleviate the issue:
``sed -i 's/ENFORCE_PWD_CHANGE=1/ENFORCE_PWD_CHANGE=0/' /etc/init.d/splunk\n``

**Comment by auzroz** [comment]
I was able to finish the Quick Start guide by changing this, yes.

**Comment by spitzzz** [comment]
Having the same issue.

**Comment by billbartlett** [comment]
What options are you using when you experience this error?  I just launched an unedited quickstart template in us-west-1 without any issue.  My options of note were: 

2 AZ
c4.2xlarge indexer instance type, 3 indexers
no pre-installed apps

Any additional information would be great so that I can replicate the issues seen in this thread.

**Comment by billbartlett** [comment]
This should be fixed now with [PR#38](https://github.com/aws-quickstart/quickstart-splunk-enterprise/pull/38)

**Comment by augwyl** [comment]
I am still experiencing the same issue: CREATE_FAILED AWS::EC2::Instance SplunkCM Failed

I just launched an unedited quickstart template in ap-southeast-2 region. My options of note were:

3 AZ
c4.2xlarge indexer instance type, 3 indexers
no pre-installed apps

still failed
